#!/bin/bash
# shellcheck disable=SC2086
# shellcheck disable=SC1091
# shellcheck disable=SC1090
# shellcheck disable=SC1003
# shellcheck disable=SC2034
# shellcheck disable=SC2154
# shellcheck disable=SC2016
# shellcheck disable=SC2015
# shellcheck disable=SC2143
#start:code
#!/bin/bash
if [ -e ~/.config/danime.cfg ]; then
	source ~/.config/danime.cfg
else
	readonly MEDIA_ROOT='/mnt/Multimedia'
	ANIME_PATH=$MEDIA_ROOT/Anime
	CARTOON_PATH=$MEDIA_ROOT/Animetion-Movie/Series
	MOVIE_PATH=$MEDIA_ROOT/Movie
	TV_SERIES_PATH=$MOVIE_PATH/Series
	POWER_RANGERS_PATH=$MOVIE_PATH/Power\ Rangers
	CONTINUE=true
	NORESET=false
	DOWNLOAD_ALL=false
	EP_LIST=false
	RSOLV=3
	FORCE=
	SEARCHSTR=
	TYPE=anime
fi
if [ -n "$AP" ]; then
	ANIME_PATH="$AP"
fi
if [[ $ANIME_PATH =~ @/* ]]; then
	ANIME_PATH="$ANIME_ROOT/${ANIME_PATH#*/}"
fi
if [[ -z $ANIME_PATH ]]; then
	readonly ANIME_PATH="$ANIME_ROOT"
fi
if [[ ! -d $ANIME_PATH ]]; then
	mkdir -p "$ANIME_PATH" &> /dev/null || exit 1
fi
check_deps() {
	a=0
	for n in "$@"; do
		if ! type $n &> /dev/null; then
			echo "Please install $n or make sure it is in your path."
			let a=a+1
		fi
	done
	return $a
}
check_deps spinner libbash tput wget cd echo mkdir printf read rm curl lsof sleep python3 || exit $?
. spinner
. libbash
#variables
sp=$sp31
SPINNER_DELAY=0.04
#main
ANIME_PATH="${ANIME_PATH:-$MEDIA_ROOT/Anime}"
CARTOON_PATH="${CARTOON_PATH:-$MEDIA_ROOT/Animetion-Movie/Series}"
MOVIE_PATH="${MOVIE_PATH:-$MEDIA_ROOT/Movie}"
POWER_RANGERS_PATH="${POWER_RANGERS_PATH:-$MOVIE_PATH/Power Rangers}"
CONTINUE=${CONTINUE:-true}
NORESET=${NORESET:-false}
DOWNLOAD_ALL=${DOWNLOAD_ALL:-false}
EP_LIST=${EP_LIST:-false}
FORCE=
SEARCHSTR=
#end:code

