#!/bin/bash
#start:code
#!/bin/bash
# shellcheck disable=SC2086
# shellcheck disable=SC1091
# shellcheck disable=SC1090
# shellcheck disable=SC1003
# shellcheck disable=SC2034
# shellcheck disable=SC2154
# shellcheck disable=SC2016
# shellcheck disable=SC2015
# shellcheck disable=SC2143
((def_header)) && return 0 || def_header=1
# VERSION
if [ -f ~/.config/danime.cfg ]; then
	source ~/.config/danime.cfg
else
	readonly MEDIA_ROOT='/mnt/Multimedia'
	ANIME_PATH=$MEDIA_ROOT/Anime
	CARTOON_PATH=$MEDIA_ROOT/Animetion-Movie/Series
	MOVIE_PATH=$MEDIA_ROOT/Movie
	TV_SERIES_PATH=$MOVIE_PATH/Series
	POWER_RANGERS_PATH=$MOVIE_PATH/Power\ Rangers
	NOBREAK=true
	NORESET=false
	DOWNLOAD_ALL=false
	FILE_LIST=false
	RSOLV=3
	FORCE=
	SEARCHSTR=
	TYPE=anime
	PREFERRED_TR=${PREFERRED_TR:-dub}
fi
if [ -n "$AP" ]; then
	ANIME_PATH="$AP"
fi
if [[ $ANIME_PATH = @* ]]; then
	ANIME_PATH="$MEDIA_ROOT/${ANIME_PATH#@*}"
fi
if [[ -z $ANIME_PATH ]]; then
	readonly ANIME_PATH="$MEDIA_ROOT/Anime"
fi
if [[ ! -d $ANIME_PATH ]]; then
	mkdir -p "$ANIME_PATH" &> /dev/null || exit 1
fi
check_deps()
{
	check_deps_py3()
	{
		python3 -c "import $1" &> /dev/null || (echo "Please install 'python3-$1'." && return 1)
	}
	check_deps_x11()
	{
		if [[ -n $DISPLAY ]]; then
			type $1 &> /dev/null || (echo "Please install '$1' or make sure it is in your path." && return 1)
		else
			return 0
		fi
	}
	check_deps_lib()
	{
		if echo "$1" | grep -q ':'; then
			type ${1##*:} &> /dev/null || (echo "Please install 'lib${1%%:*}' or make sure '${1##*:}' is in your path." && return 1)
		else
			find /lib{,64} /usr/lib{,64} /usr/local/lib{,64} -name "lib${1%%:*}*.so*" &> /dev/null || (echo "Please install 'lib${1%%:*}'." && return 1)
		fi
	}
	check_deps_bin()
	{
		type $1 &> /dev/null || (echo "Please install '$1' or make sure it is in your path." && return 1)
	}
	a=0
	for n in "$@"; do
		if ! "check_deps_$(echo "$n" | cut -d: -f1)" "$(echo "$n" | cut -d: -f2-)"; then
			((a = a + 1))
		fi
	done
	return $a
}
check_deps bin:awk bin:bash bin:dos2unix bin:cd \
	bin:curl bin:cut bin:dd bin:echo \
	bin:false bin:ffmpeg bin:ffprobe \
	bin:grep bin:head bin:jq bin:libbash \
	bin:lsof bin:mkdir bin:mv bin:printf \
	py3:json py3:numpy py3:requests bin:python3 \
	bin:read bin:readonly bin:rm bin:sed \
	bin:sha256sum bin:sleep bin:sort bin:spinner \
	bin:stat bin:tac bin:tail bin:tput bin:tr \
	bin:true bin:wc bin:wget bin:chromedriver \
	bin:gdbus bin:chromium
x11:notify-send    lib:xml2-util:xmllint bin:js-beautify bin:tee || exit $?
. spinner
. libbash
#variables
sp=$sp18
SPINNER_DELAY=0.07
#main
ANIME_PATH="${ANIME_PATH:-$MEDIA_ROOT/Anime}"
CARTOON_PATH="${CARTOON_PATH:-$MEDIA_ROOT/Animetion-Movie/Series}"
MOVIE_PATH="${MOVIE_PATH:-$MEDIA_ROOT/Movie}"
POWER_RANGERS_PATH="${POWER_RANGERS_PATH:-$MOVIE_PATH/Power Rangers}"
NOBREAK=${NOBREAK:-true}
NORESET=${NORESET:-false}
DOWNLOAD_ALL=${DOWNLOAD_ALL:-false}
FILE_LIST=${FILE_LIST:-false}
FORCE=
SEARCHSTR=
PREFERRED_TR=${PREFERRED_TR:-dub}
#end:code
