#!/bin/bash
# shellcheck disable=SC2015
DEBUG=${DEBUG:-false}
#start:code
ellipsis() {
	python3 -c "from sys import argv
l=int(int(argv[1])/2)
if len(' '.join(argv[2:]))>l*2:
	print(' '.join(argv[2:])[0:l],'...',' '.join(argv[2:])[-l:],sep='')
else:
	print(' '.join(argv[2:]),sep='')" "$@"
}
clear_line() {
	tput sc
	for ((i = 0; i <= $1; i++)); do
		printf "\r%-${COLUMNS}s"
	done
	tput rc
}
expand_limit() {
	${DEBUG:-false} && set -x
	if [[ $1 =~ ^[[:digit:]]+-$ ]]; then
		local n=${1%%-*}
		for ((i = n; i <= $2; i++)); do
			((i <= $2)) && printf "%d " "$i"
		done
	else
		for n in $(echo "$1" | cut -d, -f1- --output-delimiter=' '); do
			if [[ $n =~ ^[[:digit:]]+-[[:digit:]]+$ ]]; then
				i=${n%%-*}
				j=${n##*-}
				((j <= $2)) && expand_limit "$i-" "$j" || expand_limit "$i-" "$2"
			elif [[ $n =~ ^[[:digit:]]+$ ]]; then
				((n <= $2)) && printf "%d " "$n"
			else
				expand_limit "$n" "$2"
			fi
		done
	fi | tr \  \\n | sort -nu | tr \\n \  | sed 's| $|\n|g'
	${DEBUG:-false} && set +x
	return 0
}
byte_mr() {
	sed '
	s/\([0-9][0-9]*\(\.[0-9]\+\)\?\)[kK]/\1*1000/g;
	s/\([0-9][0-9]*\(\.[0-9]\+\)\?\)[mM]/\1*1000000/g
	' < /dev/stdin | bc | sed 's/\..*$//'
}
validate_limit() {
	if ! echo "$1" | grep -q '^[[:digit:],-]*$'; then
		return 1
	fi
	if [[ $1 =~ ^[[:digit:]]-$ ]]; then
		return 0
	elif [[ $1 =~ [[:digit:]]+-[[:digit:]]+ ]]; then
		local i=${1%%-*}
		local j=${1##*-}
		if ((i < j)); then
			return 0
		else
			return 1
		fi
	else
		return 0
	fi
}
srand()
{
python3 -c 'import numpy as np
from sys import argv
def random_spaced(low, high, delta, n, size=1):
	"""
	Choose n random values between low and high, with minimum spacing delta.
		If size is None, one sample is returned.
	Set size=m (an integer) to return m samples.
		The values in each sample returned by random_spaced are in increasing
	order.
	"""
	empty_space = high - low - (n-1)*delta
	if empty_space < 0:
		raise ValueError("not possible")
	if size is None:
		u = np.random.rand(n)
	else:
		u = np.random.rand(size, n)
		x = empty_space * np.sort(u, axis=-1)
	return low + x + delta * np.arange(n)
for n in random_spaced(int(argv[1]),int(argv[2]),int(argv[3]),int(argv[4]))[0]:
	print(int(n))' "$@"
}
anime_cover() {
	local anime_cover_img
	anime_cover_img=$1
	#ext=${anime_cover_img##*.}
	if [ ! -e folder.jpg ]; then
		wget --no-check-certificate -nv "$anime_cover_img" -cO "cover.jpg"
		if ! grep -q cover.jpg .hidden &> /dev/null; then
			echo cover.jpg >> .hidden
		fi
	fi
}
replace_invalid() {
	if [[ $1 == dir ]]; then
		sed 's|<|＜|g;s|>|＞|g;s|:|꞉|g;s|\"|＂|g;s|/|⧸|g;s|\\|⧹|g;s|?|？|g;s|\||⫿|g;s|\*|🞵|g;s|\.$||g'
	else
		sed 's|<|＜|g;s|>|＞|g;s|:|꞉|g;s|\"|＂|g;s|/|⧸|g;s|\\|⧹|g;s|?|？|g;s|\||⫿|g;s|\*|🞵|g;s| |-|g'
	fi
}
remote_exist()
{
	if echo "$@" | grep -q http
	then
		if [[ $(wget -S --spider --no-check-certificate -q "$@" 2>&1 |awk '/HTTP\// {print $2}'|tail -1) =~ 2[[:digit:]]. ]]
		then
			return 0
		else
			return 1
		fi
	else
		return 2
	fi

}
#end:code

