#!/bin/bash
DEBUG=${DEBUG:-false}
#start:code
danime_help() {
	echo "$(basename "$0") Help:"
	echo Usage:
	printf "  %s [options] <anime name>\n" "$(basename "$0")"
	# FIXME: implement help functions
	danime_help_options
	danime_help_examples
	danime_help_env
}
danime_help_options()
{
	echo Options:
	echo $'\t'not yet implemented.
}
danime_help_examples()
{
	echo Examples:
	echo $'\t'not yet implemented.
}
danime_help_env()
{
	echo Env Variable:
	echo $'\t'not yet implemented.
}
da_get_license()
{
	echo " Copyright $(date +%Y) Ahmad Hasan Mubashshir <ahmubashshir@gmail.com>"
	echo
	echo " 'danime' is free software; you can redistribute it and/or modify"
	echo " it under the terms of the GNU General Public License as published by"
	echo " the Free Software Foundation; either version 2 of the License, or"
	echo " (at your option) any later version."
	if ${1:-false};then
		return 0
	fi
	echo
	echo " 'danime' is distributed in the hope that it will be useful,"
	echo " but WITHOUT ANY WARRANTY; without even the implied warranty of"
	echo " MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"
	echo " GNU General Public License for more details."
	echo
	echo " You should have received a copy of the GNU General Public License"
	echo " along with 'danime'; if not, write to the Free Software"
	echo " Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,"
	echo " MA 02110-1301, USA."
}
#end:code
