#!/bin/bash
# shellcheck disable=SC2086
# shellcheck disable=SC1091
# shellcheck disable=SC1090
source libbash
source spinner
source "$(dirname "$0")"/01include
DEBUG=${DEBUG:-false}
#start:code
parse_episede_id() {
	local ep_file_host ep_file_id
	ep_file_host=$(echo "$@" | jsonparser -q -b | tr -d \" | tr \[:blank:\] \  | tr -s \  | grep '^\[host\]' | cut -d\  -f2 | tr \. _)
	ep_file_id=$(echo "$@" | jsonparser -q -b | tr -d \" | tr \[:blank:\] \  | tr -s \  | grep '^\[id\]' | cut -d\  -f2)
	if [ -n "$(type -t get_url_$ep_file_host)" ]; then
		get_url_$ep_file_host "$ep_file_id" 2> /dev/null
	else
		echo unimplemented:${ep_file_host/_/.}
	fi
}

get_url_mp4upload() {
	curl "https://www.mp4upload.com/embed-$1.html" 2> /dev/null | grep 'eval(' | cut -d\> -f2- | js-beautify -xn -e \\n -k --brace-style=expand | tr -d \",\ \)\; |grep '^player\.src'|cut -d\( -f2-
}
get_url_trollvid() {
	curl -H 'range: bytes=0-' -H 'referer: https://localhost/' -w '%{redirect_url}' "$(curl -H 'accept-encoding: identity' -H 'referer: https://localhost/' "https://mp4.sh/embed/$1" --output - 2> /dev/null | grep source | tr -d \" | tr \  \\n | grep '^src' | cut -d= -f2-)" 2> /dev/null | grep '^http' | cat
}
get_url_mp4_sh() {
	curl -H 'range: bytes=0-' -H 'referer: https://localhost/' -w '%{redirect_url}' "$(curl -H 'accept-encoding: identity' -H 'referer: https://localhost/' "https://mp4.sh/embedc/$1" --output - 2> /dev/null | grep source | tr -d \" | tr \  \\n | grep '^src' | cut -d= -f2-)" 2> /dev/null | grep '^http' | cat
}

get_url_vidstreaming() {
	local url_wx1232144
    url_wx1232144=$(curl "http://vidstreaming.io/streaming.php?id=$1" 2> /dev/null | grep sources | grep 'video/mp4' | cut -d: -f2- | sed 's|[,;]$||g' | js-beautify | tr -d '[:blank:]'\' | grep '^file:' | head -1 | cut -d: -f2- | sed 's|[,;]$||g')
    if [[ $url_wx1232144 =~ ^https://redirector.googlevideo.com/videoplayback* ]];then
	    curl -I -w '%{redirect_url}\n' "$url_wx1232144" 2> /dev/null | dos2unix -f | tail -1
	else
	    url_wx1232144=$(curl "http://vidstreaming.io/streaming.php?id=$1" 2> /dev/null |grep sources|grep mp4|cut -d: -f2-|sed 's|[,;]$||g'|js-beautify|tr -d '[:blank:]'\'|grep '^file:'|head -1|cut -d: -f2-|sed 's|[,;]$||g')
	    echo "$(dirname "$url_wx1232144")/$(curl "$url_wx1232144" -H 'referer: http://vidstreaming.io/' -s|grep -v '^#'|sort|tail -1)"
	fi
	#curl 'https://hls10x.cdnfile.info/videos/hls/vhxmj2Xjiz9qoSzV_mdbFA/1556808443/91920/272663fbf6a44feff4bea6698e7e6362/dub.7.m3u8' -H 'referer: http://vidstreaming.io/' -s|grep -v '^#'|sort|tail -1
}
#end:code

